In [1]:
import numpy as np

In [8]:
a = np.random.randint(1,10, (2,4))
b = np.random.randint(1,10, (1,4))

In [9]:
a

array([[2, 1, 5, 2],
       [3, 2, 1, 7]])

In [10]:
b

array([[1, 5, 6, 2]])

In [11]:
a+b  #this is called broadcasting

array([[ 3,  6, 11,  4],
       [ 4,  7,  7,  9]])

In [7]:
#rules 

In [ ]:
#shape should be same ,start checking from right,go towards left
#if it has one in it then itll work
#any of the rows or coloumns should be same