In [1]:
import numpy as np

In [2]:
it = [19,6,2,0,1]

In [4]:
n = np.array(it)

In [5]:
type(n)

numpy.ndarray

In [9]:
twod = np.array([[1,2],[3,4]])
twod.shape

(2, 2)

In [10]:
twod

array([[1, 2],
       [3, 4]])

In [13]:
list(range(9,20,3)) #the third number is the numbers you jump from 9 to 20

[9, 12, 15, 18]

In [14]:
np.arange(6) #arange is simlar to range,will give only integers

array([0, 1, 2, 3, 4, 5])

In [16]:
np.array(range(2,4)) #will work with any data types

array([2, 3])

In [21]:
arr = np.arange(100).reshape(10,10) #multiplication of numbers in shape = number in arange,only then the reshape is possible

In [22]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
arr1 = np.arange(40)

In [29]:
arr2 = arr1.reshape(8,5)

In [30]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [31]:
arr1[1] = 2001

In [32]:
arr2

array([[   0, 2001,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [33]:
arr1 is arr2

False